### ISSUE TITLE
CI, deployment and sbt 0.13.x

### ISSUE THREAD

**Issue by davidmweber** [flyway/flyway-sbt#1]
We need to get travis up and running. My travis account can see this repo but cannot add it. I expect we should rather use the flyway travis in future. We also need to get deployment working properly. I can set this up in sbt but it needs credentials on maven and hidden some place in travis....

sbt 0.13.x is problematic because there is no plugin test framework. Cross building efforts have failed 
so far. I suggest that we maintain the 0.13.x as is in the flyway repo until we can drop support for it and
maintain support for 1.x here. Let me know what you think.

Apart from these things, we are ready to roll.

@axelfontaine ?

**Comment by axelfontaine** [comment]
TravisCI has now been enabled for this repo.

**Comment by davidmweber** [comment]
CI works. How do you manage the deployment to maven?

**Comment by axelfontaine** [comment]
The SBT plugin was never published to Maven Central and SBT wasn't happy loading the plugin artifact using the Maven convention as it expects the Scala version in the path. We therefore published it on flywaydb.org instead. See installation section at https://flywaydb.org/documentation/sbt/

A better solution would be to either check if this is now possible or publish it to another repo like bintray instead.

**Comment by davidmweber** [comment]
Build artefact is ready at https://github.com/flyway/flywaydb.org/pull/86

**Comment by davidmweber** [comment]
Seems that sbt can publish plugins directly to maven with little issue other than credentials for flyway.

**Comment by axelfontaine** [comment]
For publishing to Maven Central, please use a separate group id like `org.flywaydb.sbt` for example (instead of `org.flywaydb`), this way you won't be dependent on us to publish your releases.

**Comment by davidmweber** [comment]
Works for me.
