### ISSUE TITLE
Plugin is validating but not processing updates in migrate task

### ISSUE THREAD

**Issue by davidmweber** [flyway/flyway-sbt#14]
When running    flywayMigrate, the validation  phase is completed successfully but the migration fails to run: The output is as follows:

```
[info] [info] Database: jdbc:hsqldb:file:target/flyway_sample;shutdown=true (HSQL Database Engine 2.2)
[info] [info] Successfully cleaned schema "PUBLIC" (execution time 00:00.002s)
[info] [success] Total time: 0 s, completed 22 Feb 2018 12:28:16 PM
[info] [info] Database: jdbc:hsqldb:file:target/flyway_sample;shutdown=true (HSQL Database Engine 2.2)
[info] [info] Successfully validated 2 migrations (execution time 00:00.009s)
[info] [info] Creating Schema History table: "PUBLIC"."flyway_schema_history"
[info] [info] Current version of schema "PUBLIC": << Empty Schema >>
[info] [info] Schema "PUBLIC" is up to date. No migration necessary.
```

For some reason (presumably something in the configuration of the plugin) has changed.

**Comment by davidmweber** [comment]
Seems as if the interpretation of MigrationVersion.CURRENT is not right. We initialize this as "current" which results in no migration. If we initialise it as LATEST, we get a migration. I believe it is related to this bug: https://github.com/flyway/flyway/issues/1919

**Comment by axelfontaine** [comment]
Works as designed. If target == CURRENT it means you do not want to migrate to anything newer than what is already there.

**Comment by davidmweber** [comment]
I don't really get that. Fortunately, the defaults in the Flyway config object work great. I'll add enough code to pass through a string containing the target version to config.setTargetAsString()  and we will have a clean solution.
