### ISSUE TITLE
libraryDependencies should be move to project/plugin.sbt

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway-sbt#18]
Currently the README recommends placing `libraryDependencies` directly in `build.sbt`.

As these are dependency of the plugin, they should be moved to `project/plugin.sbt` instead to keep things clean.

**Comment by nafg** [comment]
I don't see what the point of adding flyway to libraryDependencies is, regardless.

Indeed, the flyway website doesn't mention it.

**Comment by davidmweber** [comment]
Pretty much only in build.sbt if a user calls flyway from their app. Agree it does not need to be there or in plugins.sbt. Docs updated.
