### ISSUE TITLE
Don't compile when migrating the database

### ISSUE THREAD

**Issue by davidmweber** [flyway/flyway-sbt#2]
The current plugin insists on doing a full compile before it migrates the database. The correct behaviour should be to just migrate the database or whatever without compiling. If you use a database generator like slick, you will have felt the pain.

**Comment by axelfontaine** [comment]
Don't forget that compilation is needed for Java migrations.

**Comment by MojoJojo** [comment]
Is there a way to get this to work while using the slick generator plugin? It seems like flyway plugin triggers compile which in triggers slick generator which in turn expects tables/classes to be already present. Is there a workaround?

**Comment by davidmweber** [comment]
The next version of SBT won't trigger a compile. There is a branch at https://github.com/flyway/flyway-sbt/tree/manual-plugin-enable that may help. I plan to release a plugin for flyway 5.0.x in the next few days that will have this updated.
