### ISSUE TITLE
missing tags on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [flyway/flyway-sbt#22]
https://repo1.maven.org/maven2/io/github/davidmweber/flyway-sbt_2.12_1.0/

![2018-03-07 15 31 13](https://user-images.githubusercontent.com/389787/37077080-b361d2e0-221c-11e8-8f74-28b200a96ca9.png)

<hr />

https://github.com/flyway/flyway-sbt/tags

![2018-03-07 15 31 50](https://user-images.githubusercontent.com/389787/37077079-b330b91c-221c-11e8-89ed-1693032566b6.png)

**Comment by davidmweber** [comment]
Will look at this with the upcoming 5.0.0 release.
