### ISSUE TITLE
Cross building for 0.13.16

### ISSUE THREAD

**Issue by davidmweber** [flyway/flyway-sbt#3]
The testing is done with sbt 1.x's plugin test framework which does not exist for 0.13.x (more specifically scala 2.10). If anyone knows how we should go about this, please let me know.

**Comment by axelfontaine** [comment]
You always have the option to use the method we used in the flyway-sbt-largetest module: invoke SBT itself as an end-user would. Works with any version of any tool.

**Comment by davidmweber** [comment]
Tempting. As is maintaining the 0.13.x branch as it is.

**Comment by jarreds** [comment]
Perhaps this could help somehow https://github.com/dwijnand/sbt-compat

**Comment by axelfontaine** [comment]
We decided to drop the flyway-sbt module from the main distribution for Flyway 5.0.0, so this will be the only SBT plugin going forward. I am perfectly fine if you stick to SBT 1.0+.
