### ISSUE TITLE
 Unable to resolve location classpath:db/migration

### ISSUE THREAD

**Issue by ahmadjd94** [flyway/flyway-sbt#38]
i've been trying to setup a project i've been working on with flyway-sbt 
but i keep on having the following error 👍 
```
MacBook-Pro-2:FraudApi banana$ sbt flywayMigrate
[info] Loading global plugins from /Users/banana/.sbt/1.0/plugins
[info] Loading settings for project fraudapi-build from plugins.sbt ...
[info] Loading project definition from /Users/banana/IdeaProjects/fraudman/FraudApi/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to FraudAPI (in build file:/Users/banana/IdeaProjects/fraudman/FraudApi/)
[info] Flyway Community Edition 5.2.0 by Boxfuse
[info] Database: jdbc:postgresql://localhost:5444/fraudman (PostgreSQL 10.6)
[warn] Unable to resolve location classpath:db/migration
[info] Successfully validated 0 migrations (execution time 00:00.011s)
[info] Creating Schema History table: "public"."flyway_schema_history"
[info] Current version of schema "public": << Empty Schema >>
[info] Schema "public" is up to date. No migration necessary.
[success] Total time: 1 s, completed Jan 23, 2019 4:41:47 PM
```
within build.sbt
```
flywayLocations += "db/migration"
```

**Comment by MeyerJ1** [comment]
Ensure 'db/migration' is located in the resources directory of the project. I originally had it at the root and it could not find the folder, but once I moved the scripts to the resources directory it picks them up.

**Comment by rosedo** [comment]
My spring boot app fails with the same message "Unable to resolve location classpath:db/migration"
But I did put the migration scripts in the right place src/main/resources/db/migration
There are other things in the resources directory not related to flyway that work as expected using the classpath: notation

**Comment by wombat9000** [comment]
Im experiencing a similar issue where i am getting "Unable to resolve location classpath:db/migration", but other things in the resource directory are picked up correctly.

Were you able to resolve this issue for you project?

**Comment by mamadaliev** [comment]
If you get this error, check that the path to the directory where the migrations are located is correct.

**Comment by priyankaamrutkar1** [comment]
> My spring boot app warns with the same message "Unable to resolve location classpath:db/migration" But I did put the migration scripts in the right place src/main/resources/db/migration There are other things in the resources directory not related to flyway that work as expected using the classpath: notation

thank u its working for me
