### ISSUE TITLE
Use scala-steward? 

### ISSUE THREAD

**Issue by takayahilton** [flyway/flyway-sbt#46]
**Description**
>Scala Steward is a robot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward

All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos.md) and send PR.

**Comment by davidmweber** [comment]
This is strictly a sbt plugin, not a library so I don't think scala steward (it is way cool) will help much here.
