### ISSUE TITLE
Don't enable the plugin automatically

### ISSUE THREAD

**Issue by danxmoran** [flyway/flyway-sbt#5]
This is to track flyway/flyway#1329 over here. Something about the order things are applied in now causes errors like:
```
[error] sbt.AutoPluginException: Error determining plugins for project 'server' in ...:
[error] Contradiction in selected plugins.  These plugins were both included and excluded: org.flywaydb.sbt.FlywayPlugin
```
when trying to use `.disablePlugins(FlywayPlugin)`.

**Comment by davidmweber** [comment]
I'll put out a snapshot.... Will need to consider version numbers as a break away from Flyway's versioning is indicated.

**Comment by davidmweber** [comment]
There is now a snapshot available that does not trigger other tasks. Grab it here:
```
resolvers += "Flyway" at "https://davidmweber.github.io/flyway-sbt.repo"

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.2.1-SNAPSHOT")
```
Obviously, you now need to explicitly enable the plugin. Let me know how this rolls for you all.

**Comment by davidmweber** [comment]
There is now a snapshot available that does not trigger other tasks. Grab it here:
```
resolvers += "Flyway" at "https://davidmweber.github.io/flyway-sbt.repo"

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.2.1-SNAPSHOT")
```
Obviously, you now need to explicitly enable the plugin. Let me know how this rolls for you all.

**Comment by clhodapp** [comment]
Note that it looks like the upcoming release of Flyway is likely to be 5.0 which seems like a good time to break this.

**Comment by davidmweber** [comment]
Agree. We cannot go back in version numbers  so I suggest we do an Akka HTTP and go to 10.x.x for the release. Will also set up Maven Central to deploy the plugin from org.flywaydb.sbt. As of our next version, the plugin will not be enabled by default.
