### ISSUE TITLE
User Manual is missing

### ISSUE THREAD

**Issue by watiko** [flyway/flyway-sbt#6]
https://github.com/flyway/flywaydb.org/commit/a0df498bb60399be2735d975bfe3c666280eef39#diff-55876228853abf632dec9346a4f372ec
This commit removed some flyway-sbt manuals. But there is no alternative AFAIK.

**Comment by davidmweber** [comment]
Will have to migrate this at some stage. Most likely will be part of the README. Ideas welcome.

**Comment by davidmweber** [comment]
I have draft docs up at https://davidmweber.github.io/flyway-sbt-docs/index.html.  It is a direct copy of the old docs using the Flyway style and logo (@axelfontaine: Can you confirm that this is OK with Boxfuse?). I'll bring the docs up to date over the next few days in preparation for the 5.0.0 release of the plugin.

**Comment by axelfontaine** [comment]
Exact copy of the old docs is fine. Don't forget to update the installation instructions, etc.

**Comment by davidmweber** [comment]
Here: https://davidmweber.github.io/flyway-sbt-docs/. It probably needs work and should be moved to the flyway-sbt repo under docs.
