### ISSUE TITLE
please publish to maven central instead of github pages

### ISSUE THREAD

**Issue by xuwei-k** [flyway/flyway-sbt#7]

**Comment by davidmweber** [comment]
This is planned. I cannot do it under flyway's domain so it will be under something else.

**Comment by davidmweber** [comment]
@axelfontaine I have some alternatives for publishing the plogu. 

- Publish to the existing  repo under org.flywaydb.flyway-sbt? My user name on maven central is davidmweber. 
- Register org.flywaysbt and maintain it there 

I prefer the 1st option (less confusion) but I understand the risks. Alternative 2 is manageable and potentially easier if I need collaborators or if someone else takes over the maintenance.

**Comment by axelfontaine** [comment]
What about `io.github.davidmweber:flyway-sbt`?

**Comment by davidmweber** [comment]
The setup for maven central is complete. I just need to prevent the compilation from being triggered on every flyway task and do some minor documentation updates.

**Comment by jyane** [comment]
Any updates?

**Comment by davidmweber** [comment]
Pretty much ready to roll apart from one blocker. Database migration should not trigger a recompile of Scala sources. The current plugin does trigger a compile and I just cannot find where it is being triggered. I have released a snapshot to io.github.davidmwebe (addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "5.0.0-SNAPSHOT")

**Comment by davidmweber** [comment]
It should be available in maven central when they finally propagate it... Use addSbtPlugin("org.flywaydb" % "flyway-sbt" % "5.0.0-RC1")

**Comment by axelfontaine** [comment]
Please use the `io.github.davidmweber` groupId as this avoids confusion as to who is maintaining the plugin. (You may want to update the README to reflect this)

**Comment by davidmweber** [comment]
Apologies. Fixed.
